version: '3.8'

services:
  ffc-grants-eligibility:
    build:
      context: .
      target: production
    image: ffc-grants-eligibility
    depends_on:
      - ffc-grants-eligibility-postgres
    environment:
      POSTGRES_DB: ffc_grants_eligibility
      POSTGRES_PASSWORD: ppp
      POSTGRES_USER: postgres
      POSTGRES_HOST: ffc-grants-eligibility-postgres
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: public
      EOI_QUEUE_ADDRESS: ${EOI_QUEUE_ADDRESS:-notset}
      APPLICATION_TOPIC_ADDRESS: ${APPLICATION_TOPIC_ADDRESS:-notset}
      CONTACT_TOPIC_ADDRESS: ${CONTACT_TOPIC_ADDRESS:-notset}
      ELIGIBILITY_QUEUE_ADDRESS: ${ELIGIBILITY_QUEUE_ADDRESS:-notset}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST:-notset}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD:-notset}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER:-notset}

  ffc-grants-eligibility-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: ffc_grants_eligibility
      POSTGRES_PASSWORD: ppp
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
