{{- include "ffc-helm-library.container-secret" (list . "container-secret") -}}
{{- define "container-secret" -}}
stringData:
  POSTGRES_USER: {{ .Values.postgresService.postgresUser | quote }}
{{- end -}}
